version: '3'

services:
  web:
    image: php:7.3-apache
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
    ports:
      - 80:80
    volumes:
      # - ./apache:/etc/apache2
      - ./html:/var/www/html
